function toast(message,type='success'){let e=document.querySelector('.toast');if(!e){e=document.createElement('div');e.className='toast';document.body.append(e)}e.textContent=message;e.style.background=type==='error'?'#a32e2e':'#1d3421';e.classList.add('show');setTimeout(()=>e.classList.remove('show'),3200)}
function requireAuth(){if(!localStorage.getItem('shiksha_token'))location.href='login.html'}
function logout(){localStorage.removeItem('shiksha_token');localStorage.removeItem('shiksha_user');location.href='index.html'}
function formatDate(v){return new Date(v).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'})}
function shell(active,title,body){const nav=[['dashboard.html','⌂','Dashboard'],['upload.html','⇧','Upload PDF'],['summary.html','▤','My Lessons'],['audio.html','♫','Audio Lessons'],['quiz.html','?','Quiz'],['flashcards.html','▣','Flashcards'],['profile.html','◉','Profile']];document.body.innerHTML=`<div class="app"><aside class="sidebar"><a class="brand" href="dashboard.html">Shiksha<span>AI</span></a><nav class="menu">${nav.map(x=>`<a class="${active===x[0]?'active':''}" href="${x[0]}">${x[1]} &nbsp;${x[2]}</a>`).join('')}<a href="#" onclick="logout()">↪ &nbsp;Logout</a></nav></aside><main class="content"><header class="topbar"><div><h1>${title}</h1><div class="muted">Learn smarter, one lesson at a time.</div></div><span>🎓 <b id="userName"></b></span></header>${body}</main></div>`;const u=JSON.parse(localStorage.getItem('shiksha_user')||'{}');document.querySelector('#userName').textContent=(u.name||'Student').split(' ')[0]}
function setSpeechStatus(message){document.querySelectorAll('[data-speech-status]').forEach(x=>x.textContent=message)}
function playLesson(script,voice='female'){if(!('speechSynthesis' in window)){toast('Audio playback is not supported in this browser','error');return}window.speechSynthesis.cancel();let utterance=new SpeechSynthesisUtterance(script);utterance.rate=.92;utterance.pitch=voice==='female'?1.08:.92;const voices=window.speechSynthesis.getVoices();const preferred=voices.find(v=>voice==='female'?/female|zira|samantha/i.test(v.name):/male|david|mark/i.test(v.name));if(preferred)utterance.voice=preferred;utterance.onend=()=>setSpeechStatus('Ready to play');setSpeechStatus('Playing audio lesson…');window.speechSynthesis.speak(utterance)}
function pauseLesson(){if(window.speechSynthesis.speaking){window.speechSynthesis.pause();setSpeechStatus('Paused')}}
function resumeLesson(){if(window.speechSynthesis.paused){window.speechSynthesis.resume();setSpeechStatus('Playing audio lesson…')}}
function stopLesson(){window.speechSynthesis.cancel();setSpeechStatus('Ready to play')}
